# Generated by Django 4.1.4 on 2022-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="type",
        ),
        migrations.AddField(
            model_name="movie",
            name="time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(blank=True, to="chocko.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="companies",
            field=models.ManyToManyField(blank=True, to="chocko.company"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="chocko.category"),
        ),
    ]
