# Generated by Django 4.1.4 on 2022-12-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0002_remove_movie_type_movie_time_alter_movie_actors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="content_rating",
            field=models.CharField(default="بدون محدودیت", max_length=20),
        ),
    ]
