# Generated by Django 4.1.4 on 2022-12-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0003_movie_content_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
