# Generated by Django 4.1.4 on 2022-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0005_alter_movie_imdb_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
