# Generated by Django 4.1.4 on 2022-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0006_alter_movie_imdb_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="summary",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="works",
            field=models.ManyToManyField(blank=True, to="chocko.movie"),
        ),
    ]
