# Generated by Django 4.1.4 on 2022-12-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0007_actor_birth_date_actor_summary_actor_works"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="works",
            field=models.ManyToManyField(blank=True, to="chocko.movie"),
        ),
    ]
