# Generated by Django 4.1.4 on 2022-12-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0008_company_works"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="works",
        ),
        migrations.RemoveField(
            model_name="company",
            name="works",
        ),
    ]
