# Generated by Django 4.1.4 on 2022-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0009_remove_actor_works_remove_company_works"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="chocko.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="chocko.company"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="chocko.category"
            ),
        ),
    ]
