# Generated by Django 4.1.4 on 2022-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0011_remove_actor_actorid_alter_actor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
