# Generated by Django 4.1.4 on 2022-12-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0012_category_display_name_alter_category_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Genre",
        ),
    ]
