# Generated by Django 4.1.4 on 2023-01-01 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0015_rename_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="send_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
