# Generated by Django 4.1.4 on 2023-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0017_alter_comment_author_alter_comment_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="added_groups", to="chocko.movie"
                    ),
                ),
            ],
        ),
    ]
