# Generated by Django 4.1.4 on 2023-01-05 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chocko", "0017_contentrating_country_movietype_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="saves",
            field=models.ManyToManyField(
                blank=True, related_name="saved_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
