# Generated by Django 4.1.4 on 2023-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0018_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
            ],
        ),
    ]
