# Generated by Django 4.1.4 on 2023-01-03 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0019_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="actor",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="summary",
        ),
        migrations.AddField(
            model_name="ticket",
            name="send_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chocko.movietype",
            ),
        ),
    ]
