# Generated by Django 4.1.4 on 2023-01-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0020_movietype_remove_actor_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="chocko.movietype",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="content_rating",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to="chocko.contentrating",
            ),
        ),
    ]
