# Generated by Django 4.1.4 on 2023-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0021_contentrating_alter_movie_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="country",
        ),
        migrations.AddField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="chocko.country"
            ),
        ),
    ]
