# Generated by Django 4.1.4 on 2023-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0021_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("M", "movie"), ("S", "serie"), ("U", "unknown")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="Serie",
        ),
    ]
