# Generated by Django 4.1.4 on 2023-01-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0022_movie_type_delete_serie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="stars",
        ),
    ]
