# Generated by Django 4.1.4 on 2023-01-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0024_remove_director_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="directors",
        ),
    ]
