# Generated by Django 4.1.4 on 2023-01-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0025_rename_director_movie_directors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="time",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.URLField(blank=True, null=True),
        ),
    ]
