# Generated by Django 4.1.4 on 2023-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0026_alter_movie_time_alter_movie_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="chocko.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="chocko.company"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="chocko.country"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="chocko.director"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="chocko.genre"
            ),
        ),
    ]
