# Generated by Django 4.1.4 on 2023-01-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0027_alter_movie_actors_alter_movie_companies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="hits",
            field=models.ManyToManyField(
                blank=True, related_name="movie", to="chocko.ipaddress"
            ),
        ),
    ]
