# Generated by Django 4.1.4 on 2023-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0028_ipaddress_movie_hits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
