# Generated by Django 4.1.4 on 2023-03-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chocko", "0029_alter_movie_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="added_groups", to="chocko.movie"
            ),
        ),
    ]
