# Generated by Django 4.1.4 on 2023-03-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chocko", "0031_alter_group_slug_alter_group_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="plot",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
